# Here are the sentences that will be used in the game

underrepresented_women_scientists_dict = {
    "Katherine Johnson, African American mathematician and space scientist who contributed to the US space program": "https://en.wikipedia.org/wiki/Katherine_Johnson",
    "Chien-Shiung Wu, Chinese-American physicist who made significant contributions to the Manhattan Project": "https://en.wikipedia.org/wiki/Chien-Shiung_Wu",
    "Lise Meitner, Austrian-Swedish physicist who worked on nuclear physics and helped discover nuclear fission": "https://en.wikipedia.org/wiki/Lise_Meitner",
    "Rosalind Franklin, English chemist and X-ray crystallographer whose work was instrumental in the discovery of the structure of DNA": "https://en.wikipedia.org/wiki/Rosalind_Franklin",
    "Tu Youyou, Chinese pharmaceutical chemist who discovered the antimalarial drug artemisinin": "https://en.wikipedia.org/wiki/Tu_Youyou",
    "Maryam Mirzakhani, Iranian mathematician who was the first woman to win the Fields Medal": "https://en.wikipedia.org/wiki/Maryam_Mirzakhani",
    "Cheryl Hayashi, American evolutionary biologist known for her work on spider silk": "https://en.wikipedia.org/wiki/Cheryl_Hayashi",
    "Lisa Randall, American theoretical physicist known for her work on particle physics and cosmology": "https://en.wikipedia.org/wiki/Lisa_Randall",
    "Huda Zoghbi, Lebanese-American geneticist who discovered the genetic basis of Rett syndrome": "https://en.wikipedia.org/wiki/Huda_Zoghbi",
    "Gladys West, African American mathematician who worked on the development of GPS technology": "https://en.wikipedia.org/wiki/Gladys_West",
    "Mary Jackson, African American mathematician and aerospace engineer who contributed to the US space program": "https://en.wikipedia.org/wiki/Mary_Jackson_(engineer)",
    "Mae Jemison, African American astronaut and physician who was the first African American woman to travel in space": "https://en.wikipedia.org/wiki/Mae_Jemison",
    "Chitra Ramakrishna, Indian mathematician who made significant contributions to number theory": "https://en.wikipedia.org/wiki/Chitra_Ramakrishna",
    "Nettie Stevens, American geneticist who discovered the role of sex chromosomes in determining gender": "https://en.wikipedia.org/wiki/Nettie_Stevens",
    "Carolyn Bertozzi, American chemist known for her work on bioorthogonal chemistry": "https://en.wikipedia.org/wiki/Carolyn_Bertozzi",
    "Kizzmekia Corbett, American viral immunologist who played a key role in the development of the Moderna COVID-19 vaccine": "https://en.wikipedia.org/wiki/Kizzmekia_Corbett",
    "Dame Jocelyn Bell Burnell, British astrophysicist who discovered pulsars": "https://en.wikipedia.org/wiki/Jocelyn_Bell_Burnell",
    "Joan Feynman, American astrophysicist known for her work on the sun-earth relationship and space weather": "https://en.wikipedia.org/wiki/Joan_Feynman",
    "Emmy Noether, German mathematician who made significant contributions to abstract algebra and theoretical physics": "https://en.wikipedia.org/wiki/Emmy_Noether",
    "May-Britt Moser, Norwegian neuroscientist who won the Nobel Prize in Physiology or Medicine for her work on the brain's positioning system": "https://en.wikipedia.org/wiki/May-Britt_Moser",
    "Safia Munir, Pakistani computer scientist who developed a system for detecting and predicting cyberbullying": "https://en.wikipedia.org/wiki/Safia_Akhtar_Mun",
    "Ayanna Howard, American roboticist who develops robots for children with special needs": "https://en.wikipedia.org/wiki/Ayanna_Howard",
    "Sara Seager, Canadian-American astronomer who searches for exoplanets and is known for her work on the Kepler space telescope": "https://en.wikipedia.org/wiki/Sara_Seager",
    "Adriana Ocampo, Colombian planetary geologist who has worked on NASA's space missions to Mars and Jupiter": "https://en.wikipedia.org/wiki/Adriana_Ocampo",
    "Mildred Dresselhaus, American physicist and materials scientist known for her work on carbon nanotubes and graphene": "https://en.wikipedia.org/wiki/Mildred_Dresselhaus",
    "Nergis Mavalvala, Pakistani-American astrophysicist who was part of the team that made the first detection of gravitational waves": "https://en.wikipedia.org/wiki/Nergis_Mavalvala",
    "Evelyn Boyd Granville, African American mathematician who made significant contributions to the NASA space program": "https://en.wikipedia.org/wiki/Evelyn_Boyd_Granville",
    "Ursula Franklin, German-Canadian metallurgist and materials scientist who made significant contributions to the field of archaeometry": "https://en.wikipedia.org/wiki/Ursula_Franklin",
    "Maria Goeppert-Mayer, German-American physicist who won the Nobel Prize in Physics for her work on nuclear shell structure": "https://en.wikipedia.org/wiki/Maria_Goeppert-Mayer",
    "Svetlana Savitskaya, Russian astronaut who was the first woman to perform a spacewalk": "https://en.wikipedia.org/wiki/Svetlana_Savitskaya",
    "Alycia Weinberger, American astrophysicist known for her work on the formation and evolution of planetary systems": "https://en.wikipedia.org/wiki/Alycia_Weinberger"
    }